export const SIMILAR_IMAGES_SEARCH_START = "SIMILAR_IMAGES_SEARTH_START";
export const SIMILAR_IMAGES_SEARCH_SUCCESS = "SIMILAR_IMAGES_SEARTH_SUCCESS";
export const SIMILAR_IMAGES_SEARCH_FAILURE = "SIMILAR_IMAGES_SEARTH_FAILURE";
