export const PIXABAY_IMAGE_KEYWORD_SEARCH_START = "PIXABAY_IMAGE_KEYWORD_SEARCH_START";
export const PIXABAY_IMAGE_KEYWORD_SEARCH_SUCCESS = "PIXABAY_IMAGE_KEYWORD_SEARCH_SUCCESS";
export const PIXABAY_IMAGE_KEYWORD_SEARCH_FAILURE = "PIXABAY_IMAGE_KEYWORD_SEARCH_FAILURE";

export const PIXABAY_CLEAR_ALL_IMAGES = "PIXABAY_CLEAR_ALL_IMAGES";