export const UNSPLASH_IMAGE_KEYWORD_SEARCH_START = "UNSPLASH_IMAGE_KEYWORD_SEARCH_START";
export const UNSPLASH_IMAGE_KEYWORD_SEARCH_SUCCESS = "UNSPLASH_IMAGE_KEYWORD_SEARCH_SUCCESS";
export const UNSPLASH_IMAGE_KEYWORD_SEARCH_FAILURE = "UNSPLASH_IMAGE_KEYWORD_SEARCH_FAILURE";
export const UNSPLASH_GET_RANDOM_IMAGE = "UNSPLASH_GET_RANDOM_IMAGE";
export const UNSPLASH_CLEAR_RANDOM_IMAGE = "UNSPLASH_CLEAR_RANDOM_IMAGE";


export const UNSPLASH_CLEAR_ALL_IMAGES = "UNSPLASH_CLEAR_ALL_IMAGES";