export const FETCH_FAVOURITE_IMAGES_START = "FETCH_FAVOURITE_IMAGES_START";
export const FETCH_FAVOURITE_IMAGES_SUCCESS = "FETCH_FAVOURITE_IMAGES_SUCCESS";
export const FETCH_FAVOURITE_IMAGES_FAILURE = "FETCH_FAVOURITE_IMAGES_FAILURE";


export const SAVE_FAVOURITE_IMAGE_START = "SAVE_FAVOURITE_IMAGE_START";
export const SAVE_FAVOURITE_IMAGE_SUCCESS = "SAVE_FAVOURITE_IMAGE_SUCCESS";
export const SAVE_FAVOURITE_IMAGE_FAILURE = "SAVE_FAVOURITE_IMAGE_FAILURE";



export const REMOVE_FAVOURITE_IMAGE_START = "REMOVE_FAVOURITE_IMAGE_START";
export const REMOVE_FAVOURITE_IMAGE_SUCCESS = "REMOVE_FAVOURITE_IMAGE_SUCCESS";
export const REMOVE_FAVOURITE_IMAGE_FAILURE = "REMOVE_FAVOURITE_IMAGE_FAILURE";